# m07

## Mouse Physiologic Parameters

  * Gender: Male
  * Strain: C57BL/6
  * Weight (g): 24.1
  * Vendor: Jackson Labs
  * Physical abnormalities: none
  * Protocol (https://lapdmouse.iibi.uiowa.edu/AnimalModel/)

## Aerosol Dosing

  * Particle size: 1 micron
  * Exposure time: 10 minutes
  * Relative exposure estimate: unknown

  | Time              | RR (bpm) | Vt (ml) | VE (ml/min) | I:E  |
  |:------------------|---------:|--------:|------------:|-----:|
  |Pre Aerosol        | 273      | 0.26    | 71.9        | 0.78 |
  |Post 5 Aerosol     | 218      | 0.22    | 48.7        | 0.74 |
  |Post 10 Aerosol    | 225      | 0.23    | 51.2        | 0.70 |

## Slicing Info

  * Approximate lung orientation: LAS
  * Camera: D7100, 14-bit, 200mm Nikkor Macro lens, f/16
  * Voxel size: 4.64 x 4.564x 9.52 (microns)
  * Image exposures (msec). ISO=160, all images.

  |          |   mt      |   ol    |   fl    |   rd    |       Notes           |
  |:--------:|:---------:|:-------:|:-------:|:-------:|:----------------------|
  |excitation| UVND2     | UVND2   | 485/20  | 560/20  |center wavelength/fwhm |
  |emission  | N/A       | 470/30  | 535/30  | 635/30  |      (nm)             |
  |**Image** |**Exp**    |**Exp**  |**Exp**  |**Exp**  |    **Notes**          |
  |white     |    25     |   125   |  6000   |   167   | 1 drop rhodamine B/10mL OCT |
  |cal       |    20     |    50   |    40   |   200   |                       |
  |images    |   N/A     |    50   | 15000   |   333   |                       |
  |darks     |           |    50   | 15000   |   333   |                       |

  * Notes regarding slicing:
    * Except for one long cryomicrotome stoppage at slice 903, this
      sample looks good.
      
## Airway Segmentation

  * Total centerline length: 571.87 mm
  * Number of branches: 1564
  * Number of terminal branches: 784
  * Maximum generation number: 27
  * Number of outlet areas: 1680

## Compartment Sizes and Aerosol Deposition

  * Lung volume: 1116.76 (mm^3)

Compartments | Count | Volume (mm^3)
------------ | ----- | -------------
Lung         | 1 | 1116.76
Lobes        | 5 | 223.35±102.09
Sublobes     | 56 | 19.37±20.65
Near acini   | 392 | 2.70±1.43

Lobe      | Volume (mm^3) | Average aerosol deposition
--------- | ------------- | ----------------------
left | 367.59 | 1.41±1.35
cranial | 183.05 | 1.54±1.75
middle | 134.39 | 0.96±0.89
caudal | 319.92 | 0.94±0.82
accessory | 111.81 | 1.01±0.98

## Additional Notes

  * Overall quality: A
  
