# m10

## Mouse Physiologic Parameters

  * Gender: Female
  * Strain: BALB/c
  * Weight (g): unknown
  * Vendor: Jackson Labs
  * Physical abnormalities: none
  * Protocol (https://lapdmouse.iibi.uiowa.edu/AnimalModel/)

## Aerosol Dosing

  * Particle size: 1 micron
  * Exposure time: 10 minutes
  * Relative exposure estimate: 1.12E+08 FMS

  | Time              | RR (bpm) | Vt (ml) | VE (ml/min) | I:E  |
  |:------------------|---------:|--------:|------------:|-----:|
  |Pre Aerosol        | 237      | 0.27    | 63.4        | 0.82 |
  |Post 5 Aerosol     | 229      | 0.21    | 48.6        | 0.76 |
  |Post 10 Aerosol    | 230      | 0.20    | 44.9        | 0.71 |

## Slicing Info

  * Approximate lung orientation: LAS
  * Camera: D7100, 14-bit, 200mm Nikkor Macro lens, f/16
  * Voxel size: 4.64 x 4.64 x 9.52 (microns)
  * Image exposures (msec). ISO=160, all images.

  |          |   mt      |   ol    |   fl    |   rd    |       Notes           |
  |:--------:|:---------:|:-------:|:-------:|:-------:|:----------------------|
  |excitation| UVND2     | UVND2   | 485/20  | 560/20  |center wavelength/fwhm |
  |emission  | N/A       | 470/30  | 535/30  | 635/30  |      (nm)             |
  |**Image** |**Exp**    |**Exp**  |**Exp**  |**Exp**  |    **Notes**          |
  |white     |    25     |   125   |  6000   |   167   | 1 drop rhodamine B/10mL OCT |
  |cal       |    20     |    50   |    40   |   200   |                       |
  |images    |   N/A     |    50   | 15000   |   333   |                       |
  |darks     |           |    50   | 15000   |   333   |                       |

  * Notes regarding slicing:
    * Good sample overall.
    * Lung apices have indentations probably from the mold used to freeze them.
      
## Airway Segmentation

  * Total centerline length: 524.425 mm
  * Number of branches: 1339
  * Number of terminal branches: 675
  * Maximum generation number: 25
  * Number of outlet areas: 1797

## Compartment Sizes and Aerosol Deposition

  * Lung volume: 1144.66 (mm^3)

Compartments | Count | Volume (mm^3)
------------ | ----- | -------------
Lung         | 1 | 1144.66
Lobes        | 5 | 228.93±114.91
Sublobes     | 54 | 20.74±20.94
Near acini   | 362 | 3.02±1.92

Lobe      | Volume (mm^3) | Average aerosol deposition
--------- | ------------- | ----------------------
left | 405.69 | 1.17±1.59
cranial | 193.19 | 1.58±2.21
middle | 131.73 | 0.99±1.15
caudal | 314.47 | 1.13±1.22
accessory | 99.58 | 0.80±0.79

## Additional Notes

  * Overall quality: A
  
