# m21

## Mouse Physiologic Parameters

  * Gender: Male
  * Strain: CD-1
  * Weight (g): 26.0
  * Vendor: Charles River
  * Physical abnormalities: None
  * Protocol (https://lapdmouse.iibi.uiowa.edu/AnimalModel/)

## Aerosol Dosing

  * Particle size: 2 microns
  * Exposure time: 15 minutes
  * Relative exposure estimate: TBD

  | Time              | RR (bpm) | Vt (ml) | VE (ml/min) | I:E  |
  |:------------------|---------:|--------:|------------:|-----:|
  |Pre Aerosol        | 197      | 0.32    | 63.2        | 0.81 |
  |Post 5min Aerosol  | 174      | 0.30    | 52.7        | 0.75 |
  |Post 10min Aerosol | 170      | 0.30    | 51.8        | 0.75 |

## Slicing Info

  * Approximate lung orientation: LAS
  * Camera: D7100, 14-bit, 200mm Nikkor Macro lens, f/16
  * Voxel size: 4.67 x 4.67 x 9.52 (microns)
  * Image exposures (msec). ISO=160, all images.

  |          |   mt   |   ol   |   fl   |   rd   |       Notes           |
  |:--------:|:------:|:------:|:------:|:------:|:----------------------|
  |excitation| UVND2  | UVND2  | 485/20 | 560/20 |center wavelength/fwhm |
  |emission  | N/A    |470/30  | 535/30 | 635/30 |                       |
  |**Image** |**Exp** |**Exp** |**Exp** |**Exp** |    **Notes**          |
  |white     |    33  |   200  |  8000  |   200  |Rhodamine B in OCT     |
  |cal       |    20  |   167  |    67  |   400  |                       |
  |images    |        |    67  | 20000  |  1600  |                       |
  |darks     |        |    67  | 20000  |  1600  |                       |

  * Notes regarding slicing:
    * There is a discontinuity in the trachea when the lamp turned off
    * The trachea is very hort because some of this sample was sliced
      off on a previous day
    * Overall a good sample. The aerosol signal was good.
      
## Airway Segmentation

  * Total centerline length: 582.834 mm
  * Number of branches: 1518
  * Number of terminal branches: 760
  * Maximum generation number: 26
  * Number of outlet areas: 1804

## Compartment Sizes and Aerosol Deposition

  * Lung volume: 1224.76 (mm^3)

Compartments | Count | Volume (mm^3)
------------ | ----- | -------------
Lung         | 1 | 1224.76
Lobes        | 5 | 244.95±102.52
Sublobes     | 51 | 23.63±24.27
Near acini   | 311 | 3.79±2.96

Lobe      | Volume (mm^3) | Average aerosol deposition
--------- | ------------- | ----------------------
left | 389.74 | 1.30±2.97
cranial | 243.00 | 1.59±3.52
middle | 148.36 | 0.72±2.60
caudal | 324.74 | 1.12±1.52
accessory | 118.91 | 0.80±1.17

## Additional Notes

  * Overall quality: B
  * tip of accessory lobe broke off
  * some missing distal airways
  
