# m23

## Mouse Physiologic Parameters

  * Gender: F
  * Strain: C57BL/6
  * Weight (g): 19.9
  * Vendor: Jackson Labs
  * Physical abnormalities: None
  * Protocol (https://lapdmouse.iibi.uiowa.edu/AnimalModel/)

## Aerosol Dosing

  * Particle size: 2 microns
  * Exposure time: 10 minutes
  * Relative exposure estimate: TBD

  | Time              | RR (bpm) | Vt (ml) | VE (ml/min) | I:E  |
  |:------------------|---------:|--------:|------------:|-----:|
  |Pre Aerosol        | 257      | 0.24    | 61.2        | 0.95 |
  |Post 5min Aerosol  | 232      | 0.23    | 54.1        | 1.01 |
  |Post 10min Aerosol | 209      | 0.23    | 47.1        | 1.01 |

## Slicing Info

  * Approximate lung orientation: LAS
  * Camera: D7100, 14-bit, 200mm Nikkor Macro lens, f/16
  * Voxel size: 4.68 x 4.68 x 9.52 (microns)
  * Image exposures (msec). ISO=160, all images.

  |          |   mt   |   ol   |   fl   |   rd   |       Notes           |
  |:--------:|:------:|:------:|:------:|:------:|:----------------------|
  |excitation| UVND2  | UVND2  | 485/20 | 560/20 |center wavelength/fwhm |
  |emission  | N/A    |470/30  | 535/30 | 635/30 |                       |
  |**Image** |**Exp** |**Exp** |**Exp** |**Exp** |    **Notes**          |
  |white     |    33  |   200  |  6000  |   200  |Rhodamine B in OCT     |
  |cal       |    20  |   167  |    67  |   400  |                       |
  |images    |        |    77  | 20000  |  2000  |                       |
  |darks     |        |    77  | 20000  |  2000  |                       |

  * Notes regarding slicing:
    * The tip of the right lung fell out of the OCT at the end of
      slicing.
    * Aerosol signal seemed lower than other samples from this day.
      
## Airway Segmentation

  * Total centerline length: 648.032 mm
  * Number of branches: 2017
  * Number of terminal branches: 1011
  * Maximum generation number: 26
  * Number of outlet areas: 2169

## Compartment Sizes and Aerosol Deposition

  * Lung volume: 1186.47 (mm^3)

Compartments | Count | Volume (mm^3)
------------ | ----- | -------------
Lung         | 1 | 1186.47
Lobes        | 5 | 237.29±109.66
Sublobes     | 56 | 20.57±22.73
Near acini   | 282 | 3.97±2.42

Lobe      | Volume (mm^3) | Average aerosol deposition
--------- | ------------- | ----------------------
left | 390.40 | 1.51±4.49
cranial | 198.75 | 1.25±3.48
middle | 148.31 | 1.10±1.31
caudal | 340.60 | 0.91±1.43
accessory | 108.42 | 1.06±2.95

## Additional Notes

  * Overall quality: A
    
