# m29

## Mouse Physiologic Parameters

  * Gender: F
  * Strain: CD-1
  * Weight (g): 24.9
  * Vendor: Charles River
  * Physical abnormalities: None
  * Protocol (https://lapdmouse.iibi.uiowa.edu/AnimalModel/)

## Aerosol Dosing

  * Particle size: 2 microns
  * Exposure time: 15 minutes
  * Relative exposure estimate: TBD

  | Time              | RR (bpm) | Vt (ml) | VE (ml/min) | I:E  |
  |:------------------|---------:|--------:|------------:|-----:|
  |Pre Aerosol        | 248      | 0.34    | 84.2        | 0.99 |
  |Post 7.5min Aerosol| 221      | 0.27    | 60.1        | 0.87 |
  |Post 15min Aerosol | 197      | 0.28    | 55.1        | 0.76 |

## Slicing Info

  * Approximate lung orientation: LAS
  * Camera: D7100, 14-bit, 200mm Nikkor Macro lens, f/16
  * Voxel size: 4.71 x 4.71 x 9.52 (microns)
  * Image exposures (msec). ISO=160, all images.

  |          |   mt   |   ol   |   fl   |   rd   |       Notes           |
  |:--------:|:------:|:------:|:------:|:------:|:----------------------|
  |excitation| UVND2  | UVND2  | 485/20 | 560/20 |center wavelength/fwhm |
  |emission  | N/A    |470/30  | 535/30 | 635/30 |                       |
  |**Image** |**Exp** |**Exp** |**Exp** |**Exp** |    **Notes**          |
  |white     |    25  |   100  |  2500  |   100  |Rhodamine B in OCT     |
  |cal       |    20  |   125  |    67  |   400  |                       |
  |images    |        |    77  | 15000  |  2000  |                       |
  |darks     |        |    77  | 15000  |  2000  |                       |

  * Notes regarding slicing:
    * Trachea might be a little misshapen.
    * Good aerosol signal.
    * Good sample.
    
## Airway Segmentation

  * Total centerline length: 589.996 mm
  * Number of branches: 1458
  * Number of terminal branches: 731
  * Maximum generation number: 25
  * Number of outlet areas: 2064

## Compartment Sizes and Aerosol Deposition

  * Lung volume: 1165.83 (mm^3)

Compartments | Count | Volume (mm^3)
------------ | ----- | -------------
Lung         | 1 | 1165.83
Lobes        | 5 | 233.17±91.33
Sublobes     | 57 | 19.88±19.81
Near acini   | 355 | 3.08±1.99

Lobe      | Volume (mm^3) | Average aerosol deposition
--------- | ------------- | ----------------------
left | 361.99 | 1.12±3.40
cranial | 214.29 | 2.12±4.68
middle | 147.33 | 1.03±2.22
caudal | 313.55 | 0.74±1.93
accessory | 128.66 | 0.84±1.83

## Additional Notes

  * Overall quality: A
  * Separation between accessory and middle lobe maybe off due to unusual shape and poor fissure visibility.
  
