renderWindow = slicer.app.layoutManager().threeDWidget(0).threeDView().renderWindow()
renderWindow.SetAlphaBitPlanes(1)
wti = vtk.vtkWindowToImageFilter()
wti.SetInputBufferTypeToRGBA()
wti.SetInput(renderWindow)
writer = vtk.vtkPNGWriter()
writer.SetFileName("C:/Users/wanju/Desktop/LAPD_Analysis/lobar_plot_3d/airwaytree/airway_centerline.png")
writer.SetInputConnection(wti.GetOutputPort())
writer.Write()